version: '3.8'

services:
  mongo:
    image: mongo:6
    ports:
      - "27018:27017"

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_DB_URI: ${MONGO_DB_URI}
    depends_on:
      - mongo