apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jsweeneyhpa                         # UPDATE: name for this HPA (e.g. engagement-api-hpa)
  namespace: jsey              # UPDATE: same namespace as deployment.yaml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jsweeneyapp                       # UPDATE: must match the deployment name in deployment.yaml
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80